import React from 'react';
import PropTypes from 'prop-types';
import I18n from '@shopgate/pwa-common/components/I18n';
import { themeConfig } from '@shopgate/pwa-common/helpers/config';
import { formatAvailableDate } from '../../helpers/isComingSoon';
// Generated by the SDK from extension-config.json (configuration, destination: frontend).
import extensionConfig from '../../config.json';

const { colors, variables, shadows } = themeConfig;
const barHeight = 46;

// Admin-configurable greyness of the bar; falls back if not (yet) delivered.
// The Developer Center delivers admin values as strings, hence parseFloat.
const DEFAULT_BAR_OPACITY = 0.6;
const configuredOpacity = parseFloat(extensionConfig.comingSoonBarOpacity);
const barOpacity = Number.isFinite(configuredOpacity) ? configuredOpacity : DEFAULT_BAR_OPACITY;

/**
 * Mirrors the theme's add-to-cart bar 1:1 so height, insets, shadow and
 * safe-area match exactly — the `product.add-to-cart-bar` portal replaces the
 * *whole* bar, so we reproduce its container/innerContainer/base/button nesting
 * (theme-ios11 pages/Product/components/AddToCartBar/style.js + .../AddToCartButton/style.js).
 * All values come from `themeConfig`; only `opacity` greys the CTA out.
 */
const styles = {
  container: {
    background: colors.light,
    boxShadow: shadows.cart.paymentBar,
    position: 'relative',
    zIndex: 2,
    overflow: 'hidden',
    paddingBottom: 'var(--safe-area-inset-bottom)',
  },
  innerContainer: {
    padding: variables.gap.small,
  },
  base: {
    height: barHeight,
    position: 'relative',
  },
  button: {
    position: 'absolute',
    right: 0,
    top: 0,
    display: 'block',
    width: '100%',
    boxSizing: 'border-box',
    textAlign: 'center',
    background: `var(--color-button-cta, ${colors.cta})`,
    color: `var(--color-button-cta-contrast, ${colors.ctaContrast})`,
    fontSize: 16,
    fontWeight: 700,
    borderRadius: 5,
    padding: `${(variables.gap.big * 0.75) - 1}px ${variables.gap.big * 0.6}px ${(variables.gap.big * 0.75) + 1}px`,
    opacity: barOpacity,
    cursor: 'not-allowed',
  },
};

/**
 * The "available on <date>" bar shown on the PDP in place of the add-to-cart bar.
 * Visually identical to the add-to-cart bar, just greyed out.
 * @param {Object} props Component props.
 * @param {Object} props.product Product or selected-variant data.
 */
const ComingSoonBar = ({ product }) => (
  <div className="coming-soon-bar" style={styles.container} data-test-id="comingSoonBar">
    <div style={styles.innerContainer}>
      <div style={styles.base}>
        <div style={styles.button}>
          <I18n.Text
            string="ext-coming-soon.available_on"
            params={{ date: formatAvailableDate(product) }}
          />
        </div>
      </div>
    </div>
  </div>
);

ComingSoonBar.propTypes = {
  product: PropTypes.shape(),
};

ComingSoonBar.defaultProps = {
  product: null,
};

export default ComingSoonBar;
