// Generated by the SDK from extension-config.json (configuration, destination: frontend).
import extensionConfig from '../config.json';

/**
 * Admin-configurable greyness of the coming-soon bars (phone + tablet).
 * The Developer Center delivers admin values as strings, hence parseFloat;
 * falls back when the value is not (yet) set.
 */
const DEFAULT_BAR_OPACITY = 0.6;
const configured = parseFloat(extensionConfig.comingSoonBarOpacity);

export const barOpacity = Number.isFinite(configured) ? configured : DEFAULT_BAR_OPACITY;
